### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by Sovina1991** [Viola-Siemens/EmeraldCraftMod#4]
### The Version of Emerald Craft

1.19.2

### Terrablender Version

2.0.1.162

### Minecraft Version

1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### Crash Side

Client Crashes

### What happened?

创建新世界的时候崩溃

### Crash report

[minecraft-exported-crash-info-2023-06-30T18-37-22.zip](https://github.com/Viola-Siemens/EmeraldCraftMod/files/11925434/minecraft-exported-crash-info-2023-06-30T18-37-22.zip)

### debug.log

[minecraft-exported-crash-info-2023-06-30T18-37-22.zip](https://github.com/Viola-Siemens/EmeraldCraftMod/files/11925435/minecraft-exported-crash-info-2023-06-30T18-37-22.zip)

### Did you isolate Emerald Craft?

I tried Emerald Craft alone and the crash doesn't occurs.

**Comment by Viola-Siemens** [comment]
Line 3748 in your latest.log, Better Village and Immersive Engineering can't work together without the datapack.
If the issue still happens after installing the datapack, that may cause by idas mod or Integrated Stronghold mod, which are both close-sourced. You can try to set `ENABLE_JEI_TRADING_SHADOW_RECIPE` to false in `config/emeraldcraft-common.toml`. If it still happens after doing this, please upload your new debug.log file.
