### ISSUE TITLE
[Crash]: 服务器地图加载完毕后崩溃

### ISSUE THREAD

**Issue by monsters-97** [Viola-Siemens/EmeraldCraftMod#5]
### The Version of Emerald Craft

3.9

### Terrablender Version

1.2.0.126

### Minecraft Version

1.18.2

### Mod Loader

Forge

### Mod Loader Version

40.2.9

### Crash Side

Server Crashes

### What happened?

When adding the Emerald Craft Mod on the client, the client opens fine and can play in the single player world at will. However, when I use the same mod on the server as on the client, after the server finishes loading the world, Emerald Craft Mod outputs error log files like crazy in the background of the server, and after the log file output is finished, the server shuts down automatically (the server is on the whole time, and there is no way to get to the server from the client after the world is loaded).
When I try to use EC alone as well as TB, the server side still outputs some error logs after the map is loaded, but after the output is done the server side opens normally and can be accessed, I don't understand what is wrong, so I would like to ask you.
Below are the logs from my server side with all modules.

### Crash report

[latest.log](https://github.com/Viola-Siemens/EmeraldCraftMod/files/12209711/latest.log)

### debug.log

[debug.log](https://github.com/Viola-Siemens/EmeraldCraftMod/files/12209713/debug.log)

### Did you isolate Emerald Craft?

I tried Emerald Craft alone and the crash doesn't occurs.

**Comment by monsters-97** [comment]
另外补充一下，在删除绿宝石工艺后服务器是可以正常运行的

**Comment by Viola-Siemens** [comment]
您提交的错误报告并不是崩溃报错后的crash report和debug.log，我看不到服务器在哪里之后终止服务了。请您再次触发一次服务器崩溃后再上传最新的报告和日志，而不是在服务器正常运行后上传当前的日志

**Comment by monsters-97** [comment]
很抱歉我上传错了crash report，现在我重新上传
[crash-2023-07-31_13.27.35-server.txt](https://github.com/Viola-Siemens/EmeraldCraftMod/files/12211731/crash-2023-07-31_13.27.35-server.txt)

**Comment by monsters-97** [comment]
很抱歉我上传错了，现在我重新上传
[crash-2023-07-31_13.27.35-server.txt](https://github.com/Viola-Siemens/EmeraldCraftMod/files/12211748/crash-2023-07-31_13.27.35-server.txt)
[debug.log](https://github.com/Viola-Siemens/EmeraldCraftMod/files/12211750/debug.log)

**Comment by Viola-Siemens** [comment]
你的服务器配置较低了，导致生成和探索区块时耗时过长引起看门狗认为服务器已经死了，触发了异常。如果不加绿宝石工艺就不会报错，我猜是加载影子配方时，其它模组添加了需要较高生成算力的配方引起了崩溃。那么你可以牺牲掉加载影子配方的功能来避免崩溃。方法是将绿宝石工艺的common config（即config/emeraldcraft-common.toml）中的ENABLE_JEI_TRADING_SHADOW_RECIPE项设为false。

**Comment by monsters-97** [comment]
问题解决了，非常感谢您
