### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by darstkuj** [Viola-Siemens/EmeraldCraftMod#7]
### 绿宝石工艺的版本

6.3

### Terrablender的版本

2.0.1.166

### Minecraft的版本

1.19.2

### 模组加载器

Forge

### 模组加载器的版本

43.3.13

### 报错端

服务器崩溃（server）

### 发生了什么？

精矿放入融化炉的一瞬间游戏卡住，然后直接退出游戏并生成崩溃报告

### 崩溃报告

[crash-2024-04-29_18.50.17-client.txt](https://github.com/Viola-Siemens/EmeraldCraftMod/files/15148962/crash-2024-04-29_18.50.17-client.txt)

### debug.log

无

### 您是否尝试隔离绿宝石工艺？

不是，我尝试了仅仅加载绿宝石工艺和它的前置但没有发生同样的崩溃。

**Comment by Viola-Siemens** [comment]
1. 你上传的是客户端的崩溃报告，并非服务端的崩溃。不知“报错端”一栏你有没有错填，如果没有，请补充上传server端崩溃报错报告。
2. 根据客户端报错信息，可以确认是Item Obliterator模组引起的崩溃，由于对方模组仅仅公开了源代码但并未开源，请联系该模组作者解决。
